site_name: Cloud.ru Labs — Знакомство с GitVerse и Evolution Container Apps

nav:
  - Введение: index.md
  - Подготовка среды: prerequisites.md
  - Lab 1 Развертывание frontend-приложения: lab1.md
  - Lab 2 Развертывание backend-приложения на Python, Go, Java Script или C#: lab2.md



theme:
  name: material
  features:
    - content.action.edit
    - content.action.view
    - navigation.footer

markdown_extensions:
  - attr_list


copyright: 2024 Powered by Cloud.ru Evolution App Services