site_name: GitVerse + Evolution Container Apps

nav:
  - Домашняя: index.md
  - Необходимые требования, подготовка среды: prerequisites.md
  - Lab 1 - Развертывание frontend-приложения на React: lab1.md
  - Lab 2 - Развертывание backend-приложения, на языке программирования на выбор python, go, java script, C#: lab2.md
  - Lab 3 - Развертывание full-stack приложения React + ASP.NET Core: lab3.md



theme:
  name: material



copyright: 2024 Powered by Cloud.ru Evolution App Services