site_name: Evolution Container Apps Labs
nav:
  - Home: index.md
  - Необходимые требования, подготовка среды: prerequisites.md
  - Lab 1 - Развертывание frontend-приложения на React: lab1.md
  - Lab 2 - Развертывание backend-приложения, на языке программирования на выбор python, go, java script, C#: lab2.md
  - Lab 3 - Развертывание full-stack приложения React + ASP.NET Core: lab3.md



theme:
  name: material

markdown_extension:
  - toc:
      toc_depth: 0

repo_url: https://github.com/clouddotru/
edit_uri: edit/main/docs

copyright: 2024 Powered by Cloud.ru Evolution App Services