name: Build and Push docker image to Evolution Artifact Registry

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CR_URI: 00e4f277-ed62-4685-88d9-71b885bd147b.cr.cloud.ru
  REPO_NAME: eca-mkdocs
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Evolution Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CR_URI }}
          username: ${{ secrets.EVO_CR_LOGIN }}
          password: ${{ secrets.EVO_CR_PWD }}
      
      - name: Docker metadata
        id: backend
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.CR_URI }}/${{ env.REPO_NAME }}
          tags: |
            type=raw,value=build{{date 'DDMMYYY'}}

      - name: Build and push to Evolution Artifact Registry
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.backend.outputs.tags }}
          platforms: linux/amd64
          provenance: false
          file: ./Dockerfile
          context: ./
