name: Build and Push docker image to Evolution Artifact Registry

on:
  push:
    branches: [ "dev" ]
env:
  CRURI: 00e4f277-ed62-4685-88d9-71b885bd147b.cr.cloud.ru
  REPO_NAME: eca-mkdocs
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Evolution Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: ${{env.CRURI}}
          username: ${{ secrets.EVO_CR_LOGIN }}
          password: ${{ secrets.EVO_CR_PWD }}
      
      - name: Docker metadata
        id: backend
        uses: docker/metadata-action@v4
        with:
          images: ${{env.CRURI}}${{env.REPO_NAME}}
          tags: |
            type=raw,value=backend{{date 'DDMMYYY'}}

      - name: Build and push to Evolution Artifact Registry
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.backend.outputs.tags }}
          platforms: linux/amd64
          file: ./Dockerfile
          context: ./
